name: Auto Format

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-format:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork) || github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          files=$(git ls-files '*.c' '*.cc' '*.cpp' '*.cxx' '*.h' '*.hpp')
          if [ -n "$files" ]; then
            clang-format -i $files
          fi

      - name: Auto commit formatted changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto format via clang-format"
          branch: ${{ github.head_ref || github.ref_name }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          file_pattern: .

