name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check formatting (clang-format)
        continue-on-error: true
        run: |
          files=$(git ls-files '*.c' '*.cc' '*.cpp' '*.cxx' '*.h' '*.hpp' | tr '\n' ' ')
          if [ -n "$files" ]; then
            echo "Checking formatting on:" $files
            clang-format --version
            # Dry-run; let auto-format job handle fixes
            clang-format -style=file -n --Werror $files || echo "format issues detected"
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [format, auto-format]
    if: ${{ needs.auto-format.result == 'success' && needs.auto-format.outputs.changes != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cpplint
        run: |
          python3 -m pip install --upgrade pip
          pip3 install cpplint

      - name: Run cpplint
        run: |
          files=$(git ls-files 'src/*.cpp' 'include/**/*.h' 2>/dev/null || true)
          if [ -n "$files" ]; then
            cpplint --filter=-legal/copyright $files
          fi

  build-x64:
    name: Build (x64)
    runs-on: windows-latest
    needs: [format, lint, auto-format]
    if: ${{ needs.auto-format.result == 'success' && needs.auto-format.outputs.changes != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (x64)
        run: cmake -S . -B build/x64 -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build (x64)
        run: cmake --build build/x64 --config Release -- /m

      - name: Upload build (x64)
        uses: actions/upload-artifact@v4
        with:
          name: build-x64
          path: build/x64

  test-x64:
    name: Test (x64)
    runs-on: windows-latest
    needs: [build-x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build (x64)
        uses: actions/download-artifact@v4
        with:
          name: build-x64
          path: build/x64

      - name: Run tests (ctest)
        run: |
          cd build/x64
          ctest -C Release --output-on-failure || echo "No tests or tests failed"

  build-arm64:
    name: Build (ARM64)
    runs-on: windows-latest
    needs: [format, lint, auto-format]
    if: ${{ needs.auto-format.result == 'success' && needs.auto-format.outputs.changes != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (ARM64)
        run: cmake -S . -B build/arm64 -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_BUILD_TYPE=Release

      - name: Build (ARM64)
        run: cmake --build build/arm64 --config Release -- /m

      - name: Upload build (ARM64)
        uses: actions/upload-artifact@v4
        with:
          name: build-arm64
          path: build/arm64

  test-arm64:
    name: Test (ARM64)
    runs-on: windows-latest
    needs: [build-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build (ARM64)
        uses: actions/download-artifact@v4
        with:
          name: build-arm64
          path: build/arm64

      - name: Run tests (ctest)
        run: |
          cd build/arm64
          ctest -C Release --output-on-failure || echo "No tests or tests failed"
  auto-format:
    name: Auto Format (commit if needed)
    runs-on: ubuntu-latest
    needs: [format]
    if: ${{ (github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork) || github.event_name == 'push' }}
    outputs:
      changes: ${{ steps.auto_commit.outputs.changes_detected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          files=$(git ls-files '*.c' '*.cc' '*.cpp' '*.cxx' '*.h' '*.hpp')
          if [ -n "$files" ]; then
            clang-format -i $files
          fi

      - name: Auto commit formatted changes
        id: auto_commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto format via clang-format"
          branch: ${{ github.head_ref || github.ref_name }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          file_pattern: .
