name: Test

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-x64:
    name: Test (x64)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (x64)
        run: cmake -S . -B build/x64 -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_MSVC_DEBUG_INFORMATION_FORMAT=ProgramDatabase -DCMAKE_CXX_FLAGS_RELEASE="/Zi" -DCMAKE_EXE_LINKER_FLAGS_RELEASE="/DEBUG"

      - name: Build (x64)
        run: cmake --build build/x64 --config Release -- /m

      - name: Run tests (ctest)
        run: |
          cd build/x64
          ctest -C Release --output-on-failure || echo "No tests or tests failed"

      # Coverage moved to dedicated workflow

  test-arm64:
    name: Test (ARM64)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (ARM64)
        run: cmake -S . -B build/arm64 -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_BUILD_TYPE=Release

      - name: Build (ARM64)
        run: cmake --build build/arm64 --config Release -- /m

      - name: Run tests (ctest)
        run: |
          cd build/arm64
          ctest -C Release --output-on-failure || echo "No tests or tests failed"
